### ISSUE TITLE
Code is not compiling proper

### ISSUE THREAD

**Issue by pbiering** [ip2location/ip2location-lookup#1]
on a Fedora 32 system having IP2Location and IP2Location-devel installed it won't compile proper:

```
make  all-am
make[1]: Entering directory '***/ip2location-lookup'
gcc -DHAVE_CONFIG_H -I.   -D _GNU_SOURCE -I/usr/include -Wno-unused-result -IlibIP2Location -Wall -g -O2 -lrt -MT ip2location-ip2location.o -MD -MP -MF .deps/ip2location-ip2location.Tpo -c -o ip2location-ip2location.o `test -f 'ip2location.c' || echo './'`ip2location.c
ip2location.c: In function 'main':
ip2location.c:345:30: warning: implicit declaration of function 'IP2Location_bin_version'; did you mean 'IP2Location_get_region'? [-Wimplicit-function-declaration]
  345 |   printf("BIN version %s\n", IP2Location_bin_version(obj));
      |                              ^~~~~~~~~~~~~~~~~~~~~~~
      |                              IP2Location_get_region
ip2location.c:345:24: warning: format '%s' expects argument of type 'char *', but argument 2 has type 'int' [-Wformat=]
  345 |   printf("BIN version %s\n", IP2Location_bin_version(obj));
      |                       ~^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                        |     |
      |                        |     int
      |                        char *
      |                       %d
mv -f .deps/ip2location-ip2location.Tpo .deps/ip2location-ip2location.Po
make[1]: *** No rule to make target 'libIP2Location/IP2Location.c', needed by 'libIP2Location/ip2location-IP2Location.o'.  Stop.
make[1]: Leaving directory '***/ip2location-lookup'
make: *** [Makefile:332: all] Error 2
```

what is the reason for that?

function IP2Location_bin_version can't be found in current IP2Location 8.2.0 -> which C-Library version is used?

also the Makefile looks broken regarding compilation of the binary...

**Comment by ip2location-com** [comment]
The application makes use of the new interface introduced in [IP2Locaiton-C 8.3.0](https://github.com/chrislim2888/IP2Location-C-Library/releases/tag/8.3.0) which available in release now.

The Makefile is working as tested from our side.

<pre>make  all-am
make[1]: Entering directory '/root/ip2location-lookup-master'
gcc -DHAVE_CONFIG_H -I.   -D _GNU_SOURCE -I/usr/include -Wno-unused-result -IlibIP2Location -Wall -g -O2 -lrt -MT ip2location-ip2location.o -MD -MP -MF .deps/ip2location-ip2location.Tpo -c -o ip2location-ip2location.o `test -f 'ip2location.c' || echo './'`ip2location.c
mv -f .deps/ip2location-ip2location.Tpo .deps/ip2location-ip2location.Po
gcc -DHAVE_CONFIG_H -I.   -D _GNU_SOURCE -I/usr/include -Wno-unused-result -IlibIP2Location -Wall -g -O2 -lrt -MT libIP2Location/ip2location-IP2Location.o -MD -MP -MF libIP2Location/.deps/ip2location-IP2Location.Tpo -c -o libIP2Location/ip2location-IP2Location.o `test -f 'libIP2Location/IP2Location.c' || echo './'`libIP2Location/IP2Location.c
mv -f libIP2Location/.deps/ip2location-IP2Location.Tpo libIP2Location/.deps/ip2location-IP2Location.Po
gcc -IlibIP2Location -Wall -g -O2 -lrt   -o ip2location ip2location-ip2location.o libIP2Location/ip2location-IP2Location.o -lrt
make[1]: Leaving directory '/root/ip2location-lookup-master'</pre>

**Comment by pbiering** [comment]
Did not notice the new library version. What is the plan about releases of that tool? Best would be to migrate into the library source tree (as it has anyhow always in sync with it) - would also make RPM packaging easier.

**Comment by ip2location-com** [comment]
Alright, we will plan for this implementation.

**Comment by ip2location-com** [comment]
The lookup script has been moved into C library.

**Comment by pbiering** [comment]
thank you, first tests looking good - is there a need to bump the version to 8.4.0 ?
Imho API version can stay on 8.3.0 while lib version can be increased to 8.3.1
when do you plan to create a release?

**Comment by ip2location-com** [comment]
The version has been published.

**Comment by pbiering** [comment]
thank you, Fedora and Enterprise Linux builds will be done today
